"""
Carbon Offset Analytics Engine

This module calculates the environmental impact and sustainability metrics 
of the renewable energy generation from the Khavda Renewable Energy Park. 
It transforms generation data into actionable ESG metrics (CO2 avoided, 
coal displaced, trees equivalent) suitable for Power BI and Streamlit dashboards.
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# ==================================================
# CONSTANTS & ASSUMPTIONS
# ==================================================
# Carbon Offset Methodology Assumptions:
# 1. GRID_EMISSION_FACTOR: 0.82 kg of CO2 is emitted per 1 kWh of electricity generated by the standard grid.
# 2. COAL_CONSUMPTION_FACTOR: 0.5 kg of coal is burned to produce 1 kWh of electricity in traditional thermal plants.
# 3. TREE_ABSORPTION_RATE: A single mature tree absorbs roughly 22 kg of CO2 annually.

GRID_EMISSION_FACTOR = 0.82  
COAL_CONSUMPTION_FACTOR = 0.5  
TREE_ABSORPTION_RATE = 22.0  

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REPORTS_DIR = os.path.join(ROOT_DIR, 'reports')
CARBON_REPORTS_DIR = os.path.join(REPORTS_DIR, 'carbon_offset')

# Define Output Paths
OUTPUT_DATA_PATH = os.path.join(ROOT_DIR, 'data', 'processed', 'carbon_offset_analytics.csv')
SUMMARY_PATH = os.path.join(CARBON_REPORTS_DIR, 'carbon_offset_summary.csv')
EXECUTIVE_KPI_PATH = os.path.join(CARBON_REPORTS_DIR, 'executive_sustainability_kpis.csv')

# Dashboard output path
DASHBOARD_PATH = os.path.join(CARBON_REPORTS_DIR, 'sustainability_dashboard_summary.png')

# Ensure directories exist
os.makedirs(os.path.join(ROOT_DIR, 'data', 'processed'), exist_ok=True)
os.makedirs(CARBON_REPORTS_DIR, exist_ok=True)


def load_data() -> pd.DataFrame:
    """Load forecasted renewable energy generation data."""
    logger.info("Loading generation dataset...")
    try:
        total = pd.read_csv(os.path.join(ROOT_DIR, 'reports', 'total_output', 'total_output_predictions.csv'))
        
        # Rename predictions to expected format
        df = total.rename(columns={'predicted_total_generation_mw': 'total_generation_mw'})
        df['date'] = pd.to_datetime(df['date'])
        
        # Enforce required columns
        req_cols = ['date', 'solar_generation_mw', 'wind_generation_mw', 'total_generation_mw', 'site_name']
        missing = [c for c in req_cols if c not in df.columns]
        if missing:
            raise ValueError(f"Dataset is missing required columns: {missing}")
            
        return df
    except Exception as e:
        logger.error(f"Failed to load generation data: {e}")
        raise


def calculate_co2_avoided(df: pd.DataFrame) -> pd.Series:
    """
    Calculate kg of CO2 avoided.
    Methodology: Convert generation to kWh (* 1000) and multiply by the grid emission factor.
    """
    logger.info("Calculating CO2 Emissions Avoided...")
    # total_generation_mw * 1000 converts MW to kW. 
    return (df['total_generation_mw'] * 1000 * GRID_EMISSION_FACTOR).round(2)


def calculate_coal_saved(df: pd.DataFrame) -> pd.Series:
    """
    Calculate kg of coal consumption displaced.
    Methodology: Convert generation to kWh (* 1000) and multiply by the coal consumption factor.
    """
    logger.info("Calculating Coal Consumption Saved...")
    return (df['total_generation_mw'] * 1000 * COAL_CONSUMPTION_FACTOR).round(2)


def calculate_trees_equivalent(co2_avoided: pd.Series) -> pd.Series:
    """
    Calculate equivalent mature trees required to absorb the avoided CO2.
    Methodology: Divide the total CO2 avoided by the annual absorption rate of one mature tree.
    """
    logger.info("Calculating Equivalent Trees Planted...")
    return (co2_avoided / TREE_ABSORPTION_RATE).round(2)


def validate_data(df: pd.DataFrame) -> bool:
    """
    Ensure no nulls and no negative values exist in the sustainability calculations.
    """
    logger.info("Applying data validation rules...")
    calc_cols = ['renewable_energy_mwh', 'co2_avoided_kg', 'coal_saved_kg', 'trees_equivalent',
                 'co2_avoided_tons', 'coal_saved_tons', 'trees_equivalent_million']
    
    if df[calc_cols].isnull().any().any():
        logger.error("Validation Error: Null values detected in sustainability calculations.")
        return False
        
    if (df[calc_cols] < 0).any().any():
        logger.error("Validation Error: Negative values detected in sustainability calculations.")
        return False
        
    logger.info("Validation passed successfully.")
    return True


def generate_kpis(df: pd.DataFrame) -> dict:
    """Aggregate total KPIs over the entire dataset."""
    logger.info("Aggregating overall sustainability KPIs...")
    
    total_co2_kg = df['co2_avoided_kg'].sum()
    total_coal_kg = df['coal_saved_kg'].sum()
    total_trees = df['trees_equivalent'].sum()
    
    kpis = {
        'Total_Renewable_Energy_Generated_MWh': df['renewable_energy_mwh'].sum().round(2),
        'Total_CO2_Avoided_kg': total_co2_kg.round(2),
        'Total_CO2_Avoided_tons': (total_co2_kg / 1000).round(2),
        'Total_Coal_Saved_kg': total_coal_kg.round(2),
        'Total_Coal_Saved_tons': (total_coal_kg / 1000).round(2),
        'Total_Trees_Equivalent': total_trees.round(2),
        'Total_Trees_Equivalent_Million': (total_trees / 1000000).round(2),
        'Average_Daily_Renewable_Generation_MWh': df['renewable_energy_mwh'].mean().round(2)
    }
    return kpis


def create_visualizations(df: pd.DataFrame):
    """Generate and save time-series line charts for the calculated metrics."""
    logger.info("Generating visualization trends...")
    try:
        # Plot 1: CO2 Avoided Trend
        plt.figure(figsize=(12, 6))
        plt.plot(df['date'], df['co2_avoided_kg'], color='#2ca02c', linewidth=1.5)
        plt.title('Daily CO2 Emissions Avoided (kg)', fontweight='bold')
        plt.xlabel('Date')
        plt.ylabel('CO2 Avoided (kg)')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(CARBON_REPORTS_DIR, 'co2_avoided_trend.png'), dpi=300)
        plt.close()

        # Plot 2: Coal Saved Trend
        plt.figure(figsize=(12, 6))
        plt.plot(df['date'], df['coal_saved_kg'], color='#7f7f7f', linewidth=1.5)
        plt.title('Daily Coal Consumption Displaced (kg)', fontweight='bold')
        plt.xlabel('Date')
        plt.ylabel('Coal Saved (kg)')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(CARBON_REPORTS_DIR, 'coal_saved_trend.png'), dpi=300)
        plt.close()

        # Plot 3: Trees Equivalent Trend
        plt.figure(figsize=(12, 6))
        plt.plot(df['date'], df['trees_equivalent'], color='#17becf', linewidth=1.5)
        plt.title('Daily Equivalent Trees Planted', fontweight='bold')
        plt.xlabel('Date')
        plt.ylabel('Equivalent Trees')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(CARBON_REPORTS_DIR, 'trees_equivalent_trend.png'), dpi=300)
        plt.close()
        # Plot 4: Sustainability Dashboard Summary
        fig, axs = plt.subplots(2, 2, figsize=(16, 10))
        axs[0, 0].plot(df['date'], df['renewable_energy_mwh'], color='#9467bd', linewidth=1.5)
        axs[0, 0].set_title('Renewable Energy Generated (MWh)', fontweight='bold')
        axs[0, 0].set_ylabel('MWh')
        
        axs[0, 1].plot(df['date'], df['co2_avoided_tons'], color='#2ca02c', linewidth=1.5)
        axs[0, 1].set_title('CO2 Avoided (Tons)', fontweight='bold')
        axs[0, 1].set_ylabel('Tons')
        
        axs[1, 0].plot(df['date'], df['coal_saved_tons'], color='#7f7f7f', linewidth=1.5)
        axs[1, 0].set_title('Coal Saved (Tons)', fontweight='bold')
        axs[1, 0].set_ylabel('Tons')
        
        axs[1, 1].plot(df['date'], df['trees_equivalent_million'], color='#17becf', linewidth=1.5)
        axs[1, 1].set_title('Trees Equivalent (Million Trees)', fontweight='bold')
        axs[1, 1].set_ylabel('Millions')
        
        for ax in axs.flat:
            ax.grid(True, alpha=0.3)
            ax.tick_params(axis='x', rotation=45)
            
        plt.tight_layout()
        plt.savefig(os.path.join(CARBON_REPORTS_DIR, 'sustainability_dashboard_summary.png'), dpi=300)
        plt.close()
        
    except Exception as e:
        logger.error(f"Error generating visualizations: {e}")
        raise


def save_results(df: pd.DataFrame, kpis: dict):
    """Save the detailed analytics dataframe and the summary KPI reports."""
    logger.info("Saving results to disk...")
    try:
        # Save main analytics dataset
        df.to_csv(OUTPUT_DATA_PATH, index=False)
        
        # Save KPIs
        kpi_df = pd.DataFrame([kpis])
        kpi_df.to_csv(SUMMARY_PATH, index=False)
        
        # Save Executive Sustainability KPIs
        exec_data = [
            {'KPI': 'Renewable Energy Generated', 'Value': kpis['Total_Renewable_Energy_Generated_MWh'], 'Unit': 'MWh'},
            {'KPI': 'CO2 Avoided', 'Value': kpis['Total_CO2_Avoided_tons'], 'Unit': 'Tons'},
            {'KPI': 'Coal Saved', 'Value': kpis['Total_Coal_Saved_tons'], 'Unit': 'Tons'},
            {'KPI': 'Trees Equivalent', 'Value': kpis['Total_Trees_Equivalent_Million'], 'Unit': 'Million Trees'}
        ]
        pd.DataFrame(exec_data).to_csv(EXECUTIVE_KPI_PATH, index=False)
        
        logger.info(f"Detailed dataset saved to: {OUTPUT_DATA_PATH}")
        logger.info(f"Summary KPIs saved to: {SUMMARY_PATH}")
        logger.info(f"Executive KPIs saved to: {EXECUTIVE_KPI_PATH}")
    except Exception as e:
        logger.error(f"Failed to save results: {e}")
        raise


def main():
    logger.info("==================================================")
    logger.info("Starting Carbon Offset Analytics Engine")
    logger.info("==================================================")
    try:
        # 1. Load Data
        df = load_data()
        
        # 2. Assign Base Renewable Metric
        # Total generation assumed as MWh equivalents for daily grouping
        df['renewable_energy_mwh'] = df['total_generation_mw'].round(2)
        
        # 3. Calculate Sustainability Offsets
        df['co2_avoided_kg'] = calculate_co2_avoided(df)
        df['coal_saved_kg'] = calculate_coal_saved(df)
        df['trees_equivalent'] = calculate_trees_equivalent(df['co2_avoided_kg'])
        
        # Calculate Executive Metrics
        df['co2_avoided_tons'] = (df['co2_avoided_kg'] / 1000).round(2)
        df['coal_saved_tons'] = (df['coal_saved_kg'] / 1000).round(2)
        df['trees_equivalent_million'] = (df['trees_equivalent'] / 1000000).round(2)
        
        # 4. Filter and Order Columns
        output_cols = [
            'date', 'site_name', 'solar_generation_mw', 'wind_generation_mw', 
            'total_generation_mw', 'renewable_energy_mwh', 
            'co2_avoided_kg', 'coal_saved_kg', 'trees_equivalent',
            'co2_avoided_tons', 'coal_saved_tons', 'trees_equivalent_million'
        ]
        df = df[output_cols]
        
        # 5. Validation Check
        if not validate_data(df):
            logger.error("Pipeline halted due to validation failures.")
            return
            
        # 6. Aggregate KPIs
        kpis = generate_kpis(df)
        
        # 7. Generate Visualizations
        create_visualizations(df)
        
        # 8. Save Data & Reports
        save_results(df, kpis)
        
        logger.info("==================================================")
        logger.info("Carbon Offset Analytics Engine Completed Successfully")
        logger.info("==================================================")
    except Exception as e:
        logger.error(f"Analytics Pipeline failed with exception: {e}")

if __name__ == "__main__":
    main()
