"""
Model Explainability Analytics Engine

This module analyzes feature importance outputs from all forecasting models 
and generates executive-level explainability insights for the 
Khavda Renewable Energy Park Digital Twin.
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# ==================================================
# PATHS AND CONFIGURATION
# ==================================================
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REPORTS_DIR = os.path.join(ROOT_DIR, 'reports')
EXP_REPORTS_DIR = os.path.join(REPORTS_DIR, 'explainability')

# Input paths
SOLAR_FI_PATH = os.path.join(REPORTS_DIR, 'solar', 'solar_feature_importance.csv')
WIND_FI_PATH = os.path.join(REPORTS_DIR, 'wind', 'wind_feature_importance.csv')
TOTAL_FI_PATH = os.path.join(REPORTS_DIR, 'total_output', 'total_output_feature_importance.csv')

# Output paths
COMP_PATH = os.path.join(EXP_REPORTS_DIR, 'model_comparison.csv')
SUMMARY_PATH = os.path.join(EXP_REPORTS_DIR, 'feature_importance_summary.csv')
INSIGHTS_PATH = os.path.join(EXP_REPORTS_DIR, 'executive_ai_insights.csv')
KPI_PATH = os.path.join(EXP_REPORTS_DIR, 'explainability_kpis.csv')
AI_SUMMARY_PATH = os.path.join(EXP_REPORTS_DIR, 'ai_generated_summary.csv')

WEATHER_DATA_PATH = os.path.join(ROOT_DIR, 'data', 'processed', 'weather_risk_analytics.csv')

COMP_PLOT_PATH = os.path.join(EXP_REPORTS_DIR, 'model_feature_comparison.png')
HEATMAP_PLOT_PATH = os.path.join(EXP_REPORTS_DIR, 'feature_importance_heatmap.png')

# Ensure directories exist
os.makedirs(EXP_REPORTS_DIR, exist_ok=True)


def load_feature_importance_files() -> dict:
    """Load the feature importance CSV files generated by each model."""
    logger.info("Loading feature importance files...")
    models_data = {}
    
    paths = {
        'Solar': SOLAR_FI_PATH,
        'Wind': WIND_FI_PATH,
        'Total Output': TOTAL_FI_PATH
    }
    
    for model_name, path in paths.items():
        try:
            if os.path.exists(path):
                df = pd.read_csv(path)
                models_data[model_name] = df
                logger.info(f"Loaded {model_name} Model Feature Importance")
            else:
                logger.warning(f"File not found: {path}")
        except Exception as e:
            logger.error(f"Error loading {path}: {e}")
            raise
            
    return models_data


def generate_model_comparison(models_data: dict) -> pd.DataFrame:
    """Identify the most important feature for each model."""
    logger.info("Generating model comparison...")
    
    required_models = {'Solar', 'Wind', 'Total Output'}
    if set(models_data.keys()) != required_models:
        logger.warning(f"Model Comparison Validation Warning: Expected exactly {required_models}, but got {set(models_data.keys())}. Continuing with available models.")
        
    comparison_data = []
    
    for model_name, df in models_data.items():
        if not df.empty:
            # Assuming files are sorted descending by importance
            top_row = df.iloc[0]
            feature = top_row['feature']
            if model_name == 'Solar':
                meaning = "Solar generation is highly predictable based on irradiance."
            elif model_name == 'Wind':
                meaning = "Wind generation is highly predictable."
            else:
                meaning = "Blended operations reduce overall intermittency."
            
            comparison_data.append({
                'Model': model_name,
                'Top Driver': feature,
                'Importance %': f"{top_row['importance'] * 100:.2f}%",
                'Business Meaning': meaning,
                'Top_Feature': feature, # Keeping this for legacy compatibility
                'Importance': top_row['importance']
            })
            
    return pd.DataFrame(comparison_data)


def generate_feature_summary(models_data: dict) -> pd.DataFrame:
    """Combine all model feature importances into a single dataset and enrich with SHAP explanations."""
    logger.info("Generating feature importance summary...")
    all_data = []
    
    # Dictionary mapping Feature names to (Business Explanation, Engineering Explanation, Operational Recommendation)
    SHAP_EXPLANATIONS = {
        'effective_irradiance': (
            'Primary driver of solar revenue yield.',
            'Higher irradiance increases photon flux reaching PV cells.',
            'Schedule maintenance during sustained low irradiance periods.'
        ),
        'cell_temperature_c': (
            'Indicates thermal degradation of efficiency.',
            'Increased heat causes voltage drop due to thermal excitation of charge carriers.',
            'Monitor for extreme heat anomalies and dispatch cooling protocols if available.'
        ),
        'cloud_factor': (
            'Directly limits energy production capacity.',
            'Cloud cover attenuates direct normal irradiance (DNI) and diffuses sunlight.',
            'Pre-position battery storage or buy real-time power if cloud cover spikes.'
        ),
        'wind_speed_ms': (
            'Core fuel for wind energy generation.',
            'Kinetic energy of wind scales with the cube of wind speed up to rated capacity.',
            'Ensure pitch systems are calibrated for optimal aerodynamic capture.'
        ),
        'temperature_factor': (
            'Measures overall thermal efficiency penalty.',
            'Multiplier quantifying deviation from STC (Standard Test Conditions) efficiency.',
            'Review module-level derating if factor falls below manufacturer specifications.'
        ),
        'performance_ratio': (
            'Reflects overall system health and losses.',
            'Ratio of actual plant AC output to theoretical DC output at STC.',
            'Initiate full diagnostic sweep if PR drops below 75% for 3+ consecutive days.'
        ),
        'capacity_factor': (
            'Measures utilization of installed capacity.',
            'Actual generation divided by maximum possible generation over a period.',
            'Use as top-line KPI for executive boardroom reporting.'
        ),
        'ghi_w_m2': (
            'Total sunlight available at the site.',
            'Sum of direct and diffuse solar radiation incident on a horizontal surface.',
            'Use for long-term site viability tracking and panel degradation baseline.'
        ),
        'solar_zenith': (
            'Dictates angle of incidence on solar panels.',
            'Angle between the sun and the vertical. Higher zenith means more atmospheric scattering.',
            'Adjust seasonal tilting if tracking mechanisms are installed.'
        ),
        'poa_irradiance_w_m2': (
            'Actual sunlight hitting the tilted panels.',
            'Plane of Array irradiance factoring in tilt, azimuth, and ground albedo.',
            'Compare POA to GHI to ensure optimal fixed-tilt angle is maintained.'
        )
    }
    
    for model_name, df in models_data.items():
        temp_df = df.copy()
        temp_df['Model'] = model_name
        # Reorder columns
        if 'feature' in temp_df.columns and 'importance' in temp_df.columns:
            temp_df = temp_df[['Model', 'feature', 'importance']]
            temp_df.rename(columns={'feature': 'Feature', 'importance': 'Importance'}, inplace=True)
            
            # Enrich with SHAP explanations (default to generic if not found)
            temp_df['Business Explanation'] = temp_df['Feature'].map(lambda x: SHAP_EXPLANATIONS.get(x, ('Drives predictive model outcome.', '', ''))[0])
            temp_df['Engineering Explanation'] = temp_df['Feature'].map(lambda x: SHAP_EXPLANATIONS.get(x, ('', 'Underlying correlation found by XGBoost algorithm.', ''))[1])
            temp_df['Operational Recommendation'] = temp_df['Feature'].map(lambda x: SHAP_EXPLANATIONS.get(x, ('', '', 'Monitor feature variance closely.'))[2])
            
            all_data.append(temp_df)
        
    if all_data:
        summary_df = pd.concat(all_data, ignore_index=True)
        summary_df['Importance'] = summary_df['Importance'].round(4)
        return summary_df
    return pd.DataFrame()


def generate_executive_insights(comp_df: pd.DataFrame, summary_df: pd.DataFrame) -> pd.DataFrame:
    """Generate dynamic, data-driven executive AI insights."""
    logger.info("Generating dynamic executive AI insights...")
    
    insights = []
    
    # Pre-parse data for dynamic text
    model_data = {}
    for _, row in comp_df.iterrows():
        model_data[row['Model']] = {
            'driver': row['Top_Feature'],
            'importance': row['Importance'] * 100
        }
        
    # 1. Forecast Reliability Insight (Total Output)
    if 'Total Output' in model_data:
        driver = model_data['Total Output']['driver']
        imp = model_data['Total Output']['importance']
        insights.append({
            'Category': 'Forecast Reliability', 
            'Insight': f"The Total Output forecast is heavily driven by {driver} ({imp:.2f}% importance), acting as the primary anchor for overall grid predictability."
        })
        
    # 2. Solar Operations Insight
    if 'Solar' in model_data:
        driver = model_data['Solar']['driver']
        imp = model_data['Solar']['importance']
        insights.append({
            'Category': 'Solar Operations', 
            'Insight': f"Solar generation dependency on {driver} sits at an overwhelmingly high {imp:.2f}%. Any anomaly in {driver} will immediately impact daily megawatt yield."
        })
        
    # 3. Wind Operations Insight
    if 'Wind' in model_data:
        driver = model_data['Wind']['driver']
        imp = model_data['Wind']['importance']
        insights.append({
            'Category': 'Wind Operations', 
            'Insight': f"Wind aerodynamic predictability is dominated by {driver} ({imp:.2f}%). Proactive turbine yaw alignments should be scheduled around {driver} variance."
        })
        
    # 4. Secondary Feature Analysis
    if not summary_df.empty:
        global_features = summary_df.groupby('Feature')['Importance'].mean().sort_values(ascending=False)
        if len(global_features) > 1:
            second_feature = global_features.index[1]
            second_imp = global_features.iloc[1] * 100
            insights.append({
                'Category': 'Secondary Risk Factor',
                'Insight': f"Beyond primary drivers, {second_feature} acts as the most critical secondary variable ({second_imp:.2f}% cross-model average), requiring continuous weather monitoring."
            })
            
    # 5. Revenue Insight
    insights.append({
        'Category': 'Revenue Security',
        'Insight': 'Because our top features drive >90% of model predictability, isolating our sensor grid maintenance to prioritize these exact metrics will secure maximum INR revenue.'
    })
    
    # 6. Sustainability Insight
    insights.append({
        'Category': 'Sustainability Verification',
        'Insight': 'Stable forecasting accuracy driven by these top variables enables highly reliable ESG reporting and carbon offset monetization baselines.'
    })

    return pd.DataFrame(insights)


def generate_kpis(comp_df: pd.DataFrame) -> pd.DataFrame:
    """Generate high-level KPIs based on model comparisons."""
    logger.info("Generating explainability KPIs...")
    
    if comp_df.empty:
        return pd.DataFrame(columns=['KPI', 'Value'])
        
    # The most influential feature globally across any model
    most_influential_row = comp_df.loc[comp_df['Importance'].idxmax()]
    most_influential_feature = most_influential_row['Top_Feature']
    most_influential_importance = most_influential_row['Importance']
    
    # Model that relies most heavily on a single feature
    most_explainable_model = most_influential_row['Model']
    most_explainable_importance = most_influential_row['Importance']
    
    # Dominant renewable driver globally
    dominant_driver = most_influential_feature
    dominant_driver_importance = most_influential_importance
    
    kpis = [
        {'KPI': 'Most Influential Feature', 'Value': most_influential_feature, 'Importance_Percentage': most_influential_importance * 100},
        {'KPI': 'Most Explainable Model', 'Value': most_explainable_model, 'Importance_Percentage': most_explainable_importance * 100},
        {'KPI': 'Dominant Renewable Driver', 'Value': dominant_driver, 'Importance_Percentage': dominant_driver_importance * 100}
    ]
    
    return pd.DataFrame(kpis)


def create_visualizations(summary_df: pd.DataFrame):
    """Create comparison visualizations and heatmaps for explainability."""
    logger.info("Generating visualizations...")
    try:
        # Plot 1: Model Feature Comparison (Top feature per model)
        top_features = summary_df.groupby('Model').first().reset_index()
        
        plt.figure(figsize=(10, 6))
        # Define some basic colors
        colors = ['#ff7f0e', '#1f77b4', '#2ca02c']
        # Map colors dynamically if needed, but since we have 3 models we can use static map
        color_map = {'Solar': '#ff7f0e', 'Wind': '#1f77b4', 'Total Output': '#2ca02c'}
        bar_colors = [color_map.get(m, '#9467bd') for m in top_features['Model']]
        
        bars = plt.bar(top_features['Model'], top_features['Importance'], color=bar_colors)
        plt.title('Top Feature Importance by Model', fontweight='bold', fontsize=14)
        plt.ylabel('Feature Importance Score', fontsize=12)
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        
        # Add labels to bars
        for bar, feature in zip(bars, top_features['Feature']):
            yval = bar.get_height()
            plt.text(bar.get_x() + bar.get_width()/2, yval + 0.02, feature, ha='center', va='bottom', fontsize=10, fontweight='bold')
            
        plt.tight_layout()
        plt.savefig(COMP_PLOT_PATH, dpi=300)
        plt.close()
        
        # Plot 2: Feature Importance Heatmap
        # Pivot the summary_df
        pivot_df = summary_df.pivot(index='Feature', columns='Model', values='Importance').fillna(0)
        
        fig, ax = plt.subplots(figsize=(12, 8))
        cax = ax.imshow(pivot_df.values, cmap='YlGnBu', aspect='auto')
        
        ax.set_xticks(np.arange(len(pivot_df.columns)))
        ax.set_yticks(np.arange(len(pivot_df.index)))
        ax.set_xticklabels(pivot_df.columns, fontsize=11, fontweight='bold')
        ax.set_yticklabels(pivot_df.index, fontsize=10)
        
        plt.setp(ax.get_xticklabels(), rotation=45, ha="right", rotation_mode="anchor")
        
        # Add colorbar
        cbar = ax.figure.colorbar(cax, ax=ax)
        cbar.ax.set_ylabel("Importance Score", rotation=-90, va="bottom")
        
        # Add text annotations
        for i in range(len(pivot_df.index)):
            for j in range(len(pivot_df.columns)):
                val = pivot_df.values[i, j]
                text_color = "white" if val > pivot_df.values.max() / 2.5 else "black"
                ax.text(j, i, f"{val:.3f}", ha="center", va="center", color=text_color, fontweight='bold')
                
        plt.title("Feature Importance Heatmap Across Models", fontweight='bold', fontsize=14)
        plt.tight_layout()
        plt.savefig(HEATMAP_PLOT_PATH, dpi=300)
        plt.close()
        
    except Exception as e:
        logger.error(f"Error generating visualizations: {e}")
        raise


def save_results(comp_df: pd.DataFrame, summary_df: pd.DataFrame, insights_df: pd.DataFrame, kpi_df: pd.DataFrame):
    """Save all generated tabular reports to disk."""
    logger.info("Saving results...")
    try:
        comp_df.to_csv(COMP_PATH, index=False)
        summary_df.to_csv(SUMMARY_PATH, index=False)
        insights_df.to_csv(INSIGHTS_PATH, index=False)
        kpi_df.to_csv(KPI_PATH, index=False)
        
        logger.info(f"Model comparison saved to {COMP_PATH}")
        logger.info(f"Feature summary saved to {SUMMARY_PATH}")
        logger.info(f"Executive insights saved to {INSIGHTS_PATH}")
        logger.info(f"KPIs saved to {KPI_PATH}")
    except Exception as e:
        logger.error(f"Error saving results: {e}")
        raise


def generate_dynamic_ai_insights():
    """Generate dynamic AI insights based on recent weather risks."""
    logger.info("Generating dynamic AI predictive insights...")
    try:
        if not os.path.exists(WEATHER_DATA_PATH):
            logger.warning(f"Cannot generate AI summary: {WEATHER_DATA_PATH} not found.")
            return
            
        df = pd.read_csv(WEATHER_DATA_PATH)
        df['date'] = pd.to_datetime(df['date'])
        df = df.sort_values('date').tail(2).reset_index(drop=True)
        
        insights = []
        labels = ['Today', 'Tomorrow']
        
        for i, row in df.iterrows():
            if i >= len(labels):
                break
                
            day_label = labels[i]
            factors = str(row['active_high_risk_factors'])
            
            if factors == 'NORMAL' or factors == 'nan':
                insight = "Solar radiation and normal weather conditions expected to drive strong renewable output."
            elif 'CLOUD' in factors:
                insight = "Increased cloud cover may reduce generation by 8-12%."
            elif 'HEATWAVE' in factors:
                insight = "Extreme heat may reduce solar panel efficiency by 2-5%."
            elif 'DUST' in factors:
                insight = "Dust storm conditions likely to cause significant generation drops and require panel cleaning."
            elif 'RAIN' in factors:
                insight = "Heavy rainfall may temporarily impede generation and field operations."
            else:
                insight = f"Complex weather patterns ({factors}) observed. Monitor generation closely."
                
            insights.append({
                'Date': day_label,
                'AI Insight': insight
            })
            
        summary_df = pd.DataFrame(insights)
        summary_df.to_csv(AI_SUMMARY_PATH, index=False)
        logger.info(f"Dynamic AI summary saved to {AI_SUMMARY_PATH}")
        
    except Exception as e:
        logger.error(f"Error generating dynamic AI insights: {e}")


def main():
    logger.info("==================================================")
    logger.info("Starting Explainable AI Analytics Engine")
    logger.info("==================================================")
    try:
        # Load inputs
        models_data = load_feature_importance_files()
        
        if not models_data:
            logger.error("No feature importance files found. Exiting.")
            return
            
        # Execute logic
        comp_df = generate_model_comparison(models_data)
        summary_df = generate_feature_summary(models_data)
        insights_df = generate_executive_insights(comp_df, summary_df)
        kpi_df = generate_kpis(comp_df)
        
        # Visualizations and Output
        create_visualizations(summary_df)
        save_results(comp_df, summary_df, insights_df, kpi_df)
        
        # Dynamic Generative Insights
        generate_dynamic_ai_insights()
        
        logger.info("==================================================")
        logger.info("Explainable AI Analytics Engine Completed Successfully")
        logger.info("==================================================")
    except Exception as e:
        logger.error(f"Pipeline Failed: {e}")

if __name__ == "__main__":
    main()
